### ISSUE TITLE
npm start não inicia ou carrega

### ISSUE THREAD

**Issue by otaviogrocha** [flaviofrancisco/ecommerce-angular#2]
Mesmo seguindo os passos do commit ["Bug angular Fix"](https://github.com/flaviofrancisco/ecommerce-angular/commit/97f7faa075fcf5a2875fbb776566537557a57bbd) o npm não inicia.

Passos realizados:

- alteração das linhas previstas no commit acima
- troca das variáveis de ambiente
- exclusão da pasta node_modules

Ao clonar um novo repositório atualizado o **npm** inicializa, porém a interface não carrega ficando em um load infinito.
Ao substituir o package.json do projeto para o do clone atualizado, ainda sim o **npm** start não inicia.

**Comment by flaviofrancisco** [comment]
- Otavio, você poderia colocar o arquivo de log ou print screen? 

- Tem alguma mensagem de erro? 

- Qual a versão do Node que você instalou? Use os comandos abaixo
    `nvm list`
    `node -v`

- Qual a versão de Angular você instalou? 
  `ng version`

- Versão que nosso projeto deve rodar

> - Angular CLI: 15.2.9
> - Node: 14.21.3
> - Package Manager: npm 6.14.18

**Comment by otaviogrocha** [comment]
Angular: 15.2.9
Node: 14.21.3
npm: 6.14.18

As versões batem, não existe mensagem de erro no terminal ou no console, apenas o loading em ambos cenários.
Testei novamente e mesmo com repositório atualizado o npm não inicia para o segundo loading infinito.

- **Imagem quando o npm inicia no repositório atualizado:**

![Capturar](https://github.com/flaviofrancisco/ecommerce-angular/assets/101598593/2c571d7b-d189-49db-85f5-a4456cde5923)
- **Loading infinito do npm:**

![image](https://github.com/flaviofrancisco/ecommerce-angular/assets/101598593/74d8d841-e73f-4f9c-b853-e9b33aa1c09e)

**Comment by otaviogrocha** [comment]
<h2>UPDATE</h2>

- <h3>Resolvido </h3>
Por algum motivo percebi que o npm start só funciona nessa aplicação quando o arquivo está no disco local C:
se o repositório local estiver em um outro disco ele dispara o npm start e não retorna nada.

Entretanto, busco uma forma de conseguir rodar o npm no disco desejado, tendo em vista segurança dos arquivos.
